### PR TITLE
RHMAP-2596 Update fh-sdk to 1.3.3

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@david-martin NuGet dep, so this looks right (even though this is not published yet)

**Comment by david-martin** [comment]
@wei-lee @edewit 
Are there other changes required for this sdk bump?

**Comment by wei-lee** [comment]
LGTM. @edewit  WDYT?

**Comment by edewit** [comment]
:+1:

**Pull request merged**
