### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Comment by david-martin** [comment]
@wei-lee @edewit Is the build error about image size a valid error?
Should we fix it?

**Comment by edewit** [comment]
fixed the build with https://github.com/feedhenry-templates/welcome-windows/pull/4 and also changed to shadowman

**Comment by david-martin** [comment]
rebased to pull in FH-sdk bump to 1.3.3 (appveyor builds were passing with the commit on the branch, but not for the PR merge branch)

**Comment by david-martin** [comment]
@wei-lee @edewit The build is failing wiht this error. Any ideas?

```
c:\projects\welcome-windows\Welcome Project Windows\Welcome Project Windows.Shared\MainPage.xaml.cs(1,7): error CS0246: The type or namespace name 'FHSDKPortable' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\welcome-windows\Welcome Project Windows\Welcome Project Windows.WindowsPhone\Welcome Project Windows.WindowsPhone.csproj]
```

**Comment by edewit** [comment]
@david-martin fixed it in https://github.com/feedhenry-templates/welcome-windows/pull/4

**Pull request merged**
